name: biometric-api
env:
  - key: SECRET_KEY
    value: config('SECRET_KEY')
deploy:
  - type: web
    name: biometric-api
    command: gunicorn biometrics.wsgi:application --bind 0.0.0.0:$PORT

    routes:
      - path: /
