# Generated by Django 4.2.2 on 2023-06-19 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_attendance_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
    ]
